/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.awt.Color;
import komunikacija.KomunikacijaSaServerom;
import niti.OcekujOdgNit;
import oper.Boje;
import oper.Operacija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Nikola
 */
public class KlijentForma extends javax.swing.JFrame {

    /**
     * Creates new form KlijentForma
     */
    public KlijentForma() {
        initComponents();
        KomunikacijaSaServerom.getInstance().poveziSe();

        OcekujOdgNit oon = new OcekujOdgNit(this);
        oon.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtP1B1 = new javax.swing.JTextField();
        txtP1B2 = new javax.swing.JTextField();
        txtP1B3 = new javax.swing.JTextField();
        txtP2B3 = new javax.swing.JTextField();
        txtP2B2 = new javax.swing.JTextField();
        txtP2B1 = new javax.swing.JTextField();
        txtP3B3 = new javax.swing.JTextField();
        txtP3B2 = new javax.swing.JTextField();
        txtP3B1 = new javax.swing.JTextField();
        txtP4B3 = new javax.swing.JTextField();
        txtP4B2 = new javax.swing.JTextField();
        txtP4B1 = new javax.swing.JTextField();
        btnpokusaj1 = new javax.swing.JButton();
        btnPokusaj2 = new javax.swing.JButton();
        btnpokusaj3 = new javax.swing.JButton();
        btnpokusaj4 = new javax.swing.JButton();
        lblPoruka = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pokusaj 1:");

        jLabel2.setText("Pokusaj 2:");

        jLabel3.setText("Pokusaj 3:");

        jLabel4.setText("Pokusaj 4:");

        txtP1B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP1B2ActionPerformed(evt);
            }
        });

        txtP2B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP2B2ActionPerformed(evt);
            }
        });

        txtP3B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP3B2ActionPerformed(evt);
            }
        });

        txtP4B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP4B2ActionPerformed(evt);
            }
        });

        btnpokusaj1.setText("Pokusaj 1");
        btnpokusaj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpokusaj1ActionPerformed(evt);
            }
        });

        btnPokusaj2.setText("Pokusaj 2");
        btnPokusaj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokusaj2ActionPerformed(evt);
            }
        });

        btnpokusaj3.setText("Pokusaj 3");
        btnpokusaj3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpokusaj3ActionPerformed(evt);
            }
        });

        btnpokusaj4.setText("Pokusaj 4");
        btnpokusaj4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpokusaj4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Poruka:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtP3B1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtP3B2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtP3B3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnpokusaj3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtP1B1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtP1B2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtP1B3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnpokusaj1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtP2B1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtP2B2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtP2B3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPokusaj2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtP4B1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtP4B2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtP4B3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnpokusaj4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtP1B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP1B2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP1B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpokusaj1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtP2B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtP2B2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtP2B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPokusaj2))
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtP3B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtP3B2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtP3B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnpokusaj3))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtP4B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtP4B2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtP4B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnpokusaj4))
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtP1B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP1B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP1B2ActionPerformed

    private void txtP2B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP2B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP2B2ActionPerformed

    private void txtP3B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP3B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP3B2ActionPerformed

    private void txtP4B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP4B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP4B2ActionPerformed

    private void btnpokusaj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpokusaj1ActionPerformed
        String broj1 = txtP1B1.getText();
        String broj2 = txtP1B2.getText();
        String broj3 = txtP1B3.getText();
        int oper = Operacija.POKUSAJ;

        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(oper);
        kz.setBroj1(broj1);
        kz.setBroj2(broj2);
        kz.setBroj3(broj3);
        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
    }//GEN-LAST:event_btnpokusaj1ActionPerformed

    private void btnPokusaj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokusaj2ActionPerformed
        String broj1 = txtP2B1.getText();
        String broj2 = txtP2B2.getText();
        String broj3 = txtP2B3.getText();
        int oper = Operacija.POKUSAJ;

        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(oper);
        kz.setBroj1(broj1);
        kz.setBroj2(broj2);
        kz.setBroj3(broj3);
        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
    }//GEN-LAST:event_btnPokusaj2ActionPerformed

    private void btnpokusaj3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpokusaj3ActionPerformed
        String broj1 = txtP3B1.getText();
        String broj2 = txtP3B2.getText();
        String broj3 = txtP3B3.getText();
        int oper = Operacija.POKUSAJ;

        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(oper);
        kz.setBroj1(broj1);
        kz.setBroj2(broj2);
        kz.setBroj3(broj3);
        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
    }//GEN-LAST:event_btnpokusaj3ActionPerformed

    private void btnpokusaj4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpokusaj4ActionPerformed
        String broj1 = txtP4B1.getText();
        String broj2 = txtP4B2.getText();
        String broj3 = txtP4B3.getText();
        int oper = Operacija.POKUSAJ;

        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(oper);
        kz.setBroj1(broj1);
        kz.setBroj2(broj2);
        kz.setBroj3(broj3);
        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
    }//GEN-LAST:event_btnpokusaj4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokusaj2;
    private javax.swing.JButton btnpokusaj1;
    private javax.swing.JButton btnpokusaj3;
    private javax.swing.JButton btnpokusaj4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblPoruka;
    private javax.swing.JTextField txtP1B1;
    private javax.swing.JTextField txtP1B2;
    private javax.swing.JTextField txtP1B3;
    private javax.swing.JTextField txtP2B1;
    private javax.swing.JTextField txtP2B2;
    private javax.swing.JTextField txtP2B3;
    private javax.swing.JTextField txtP3B1;
    private javax.swing.JTextField txtP3B2;
    private javax.swing.JTextField txtP3B3;
    private javax.swing.JTextField txtP4B1;
    private javax.swing.JTextField txtP4B2;
    private javax.swing.JTextField txtP4B3;
    // End of variables declaration//GEN-END:variables

    public void srediNije(ServerskiOdgovor so) {
        lblPoruka.setText(so.getPoruka());
        btnpokusaj1.setEnabled(false);
        btnPokusaj2.setEnabled(false);
        btnpokusaj3.setEnabled(false);
        btnpokusaj4.setEnabled(false);
        txtP1B1.setEnabled(false);
        txtP1B2.setEnabled(false);
        txtP1B3.setEnabled(false);
        txtP2B1.setEnabled(false);
        txtP2B2.setEnabled(false);
        txtP2B3.setEnabled(false);
        txtP3B1.setEnabled(false);
        txtP3B2.setEnabled(false);
        txtP3B3.setEnabled(false);
        txtP4B1.setEnabled(false);
        txtP4B2.setEnabled(false);
        txtP4B3.setEnabled(false);

    }

    public void srediJeste(ServerskiOdgovor so) {
        lblPoruka.setText(so.getPoruka());
        btnpokusaj1.setEnabled(true);
        btnPokusaj2.setEnabled(true);
        btnpokusaj3.setEnabled(true);
        btnpokusaj4.setEnabled(true);
    }

    public void srediIgra() {
        lblPoruka.setText("Igra je pocela, vi ste na potezu");
        btnpokusaj1.setEnabled(true);
        btnPokusaj2.setEnabled(false);
        btnpokusaj3.setEnabled(false);
        btnpokusaj4.setEnabled(false);
        txtP1B1.setEnabled(true);
        txtP1B2.setEnabled(true);
        txtP1B3.setEnabled(true);
        txtP2B1.setEnabled(false);
        txtP2B2.setEnabled(false);
        txtP2B3.setEnabled(false);
        txtP3B1.setEnabled(false);
        txtP3B2.setEnabled(false);
        txtP3B3.setEnabled(false);
        txtP4B1.setEnabled(false);
        txtP4B2.setEnabled(false);
        txtP4B3.setEnabled(false);

    }

    public void srediNeIgra() {
        lblPoruka.setText("Igra je pocela, protivnik je na potezu");
        btnpokusaj1.setEnabled(false);
        btnPokusaj2.setEnabled(false);
        btnpokusaj3.setEnabled(false);
        btnpokusaj4.setEnabled(false);
        txtP1B1.setEnabled(false);
        txtP1B2.setEnabled(false);
        txtP1B3.setEnabled(false);
        txtP2B1.setEnabled(false);
        txtP2B2.setEnabled(false);
        txtP2B3.setEnabled(false);
        txtP3B1.setEnabled(false);
        txtP3B2.setEnabled(false);
        txtP3B3.setEnabled(false);
        txtP4B1.setEnabled(false);
        txtP4B2.setEnabled(false);
        txtP4B3.setEnabled(false);
        pack();
    }

    public void srediPrviCrvena(int red) {
        if (red == 1) {
            txtP1B1.setForeground(Color.RED);
        } else if (red == 2) {
            txtP2B1.setForeground(Color.RED);
        } else if (red == 3) {
            txtP3B1.setForeground(Color.RED);

        } else if (red == 4) {
            txtP4B1.setForeground(Color.RED);
        }
    }

    public void srediPrviZuta(int red) {
        if (red == 1) {
            txtP1B1.setForeground(Color.YELLOW);
        } else if (red == 2) {
            txtP2B1.setForeground(Color.YELLOW);
        } else if (red == 3) {
            txtP3B1.setForeground(Color.YELLOW);

        } else if (red == 4) {
            txtP4B1.setForeground(Color.YELLOW);
        }
    }

    public void srediPrviZelena(int red) {
        if (red == 1) {
            txtP1B1.setForeground(Color.GREEN);
        } else if (red == 2) {
            txtP2B1.setForeground(Color.GREEN);
        } else if (red == 3) {
            txtP3B1.setForeground(Color.GREEN);

        } else if (red == 4) {
            txtP4B1.setForeground(Color.GREEN);
        }
    }

    public void srediIgra2(int brojac) {
        lblPoruka.setText("Vi ste na potezu");
        if (brojac == 1) {
            btnpokusaj1.setEnabled(true);
            btnPokusaj2.setEnabled(false);
            btnpokusaj3.setEnabled(false);
            btnpokusaj4.setEnabled(false);
            txtP1B1.setEnabled(true);
            txtP1B2.setEnabled(true);
            txtP1B3.setEnabled(true);
            txtP2B1.setEnabled(false);
            txtP2B2.setEnabled(false);
            txtP2B3.setEnabled(false);
            txtP3B1.setEnabled(false);
            txtP3B2.setEnabled(false);
            txtP3B3.setEnabled(false);
            txtP4B1.setEnabled(false);
            txtP4B2.setEnabled(false);
            txtP4B3.setEnabled(false);

        } else if (brojac == 2) {
            btnpokusaj1.setEnabled(false);
            btnPokusaj2.setEnabled(true);
            btnpokusaj3.setEnabled(false);
            btnpokusaj4.setEnabled(false);
            txtP1B1.setEditable(false);
            txtP1B2.setEditable(false);
            txtP1B3.setEditable(false);
            txtP2B1.setEnabled(true);
            txtP2B2.setEnabled(true);
            txtP2B3.setEnabled(true);
            txtP3B1.setEnabled(false);
            txtP3B2.setEnabled(false);
            txtP3B3.setEnabled(false);
            txtP4B1.setEnabled(false);
            txtP4B2.setEnabled(false);
            txtP4B3.setEnabled(false);

        } else if (brojac == 3) {
            btnpokusaj1.setEnabled(false);
            btnPokusaj2.setEnabled(false);
            btnpokusaj3.setEnabled(true);
            btnpokusaj4.setEnabled(false);
            txtP1B1.setEditable(false);
            txtP1B2.setEditable(false);
            txtP1B3.setEditable(false);
            txtP2B1.setEditable(false);
            txtP2B2.setEditable(false);
            txtP2B3.setEditable(false);
            txtP3B1.setEnabled(true);
            txtP3B2.setEnabled(true);
            txtP3B3.setEnabled(true);
            txtP4B1.setEnabled(false);
            txtP4B2.setEnabled(false);
            txtP4B3.setEnabled(false);

        } else {
            btnpokusaj1.setEnabled(false);
            btnPokusaj2.setEnabled(false);
            btnpokusaj3.setEnabled(false);
            btnpokusaj4.setEnabled(true);
            txtP1B1.setEditable(false);
            txtP1B2.setEditable(false);
            txtP1B3.setEditable(false);
            txtP2B1.setEditable(false);
            txtP2B2.setEditable(false);
            txtP2B3.setEditable(false);
            txtP3B1.setEditable(false);
            txtP3B2.setEditable(false);
            txtP3B3.setEditable(false);
            txtP4B1.setEnabled(true);
            txtP4B2.setEnabled(true);
            txtP4B3.setEnabled(true);

        }

    }

    public void srediNeIgra2() {
        lblPoruka.setText("Protivnik je na potezu");
        btnpokusaj1.setEnabled(false);
        btnPokusaj2.setEnabled(false);
        btnpokusaj3.setEnabled(false);
        btnpokusaj4.setEnabled(false);

    }

    public void srediDrugiZelena(int brojac) {
        if (brojac == 1) {
            txtP1B2.setForeground(Color.GREEN);
        } else if (brojac == 2) {
            txtP2B2.setForeground(Color.GREEN);
        } else if (brojac == 3) {
            txtP3B2.setForeground(Color.GREEN);

        } else if (brojac == 4) {
            txtP4B2.setForeground(Color.GREEN);
        }
    }

    public void srediDrugiZuta(int brojac) {

        if (brojac == 1) {
            txtP1B2.setForeground(Color.YELLOW);
        } else if (brojac == 2) {
            txtP2B2.setForeground(Color.YELLOW);
        } else if (brojac == 3) {
            txtP3B2.setForeground(Color.YELLOW);

        } else if (brojac == 4) {
            txtP4B2.setForeground(Color.YELLOW);
        }
    }

    public void srediDrugiCrvena(int brojac) {
        if (brojac == 1) {
            txtP1B2.setForeground(Color.RED);
        } else if (brojac == 2) {
            txtP2B2.setForeground(Color.RED);
        } else if (brojac == 3) {
            txtP3B2.setForeground(Color.RED);

        } else if (brojac == 4) {
            txtP4B2.setForeground(Color.RED);
        }
    }

    public void srediTreciZelena(int brojac) {
        if (brojac == 1) {
            txtP1B3.setForeground(Color.GREEN);
        } else if (brojac == 2) {
            txtP2B3.setForeground(Color.GREEN);
        } else if (brojac == 3) {
            txtP3B3.setForeground(Color.GREEN);

        } else if (brojac == 4) {
            txtP4B3.setForeground(Color.GREEN);
        }
    }

    public void srediTreciZuta(int brojac) {
        if (brojac == 1) {
            txtP1B3.setForeground(Color.YELLOW);
        } else if (brojac == 2) {
            txtP2B3.setForeground(Color.YELLOW);
        } else if (brojac == 3) {
            txtP3B3.setForeground(Color.YELLOW);

        } else if (brojac == 4) {
            txtP4B3.setForeground(Color.YELLOW);
        }
    }

    public void srediTreciCrvena(int brojac) {
        if (brojac == 1) {
            txtP1B3.setForeground(Color.RED);
        } else if (brojac == 2) {
            txtP2B3.setForeground(Color.RED);
        } else if (brojac == 3) {
            txtP3B3.setForeground(Color.RED);

        } else if (brojac == 4) {
            txtP4B3.setForeground(Color.RED);
        }
    }

    public void srediKraj(String poruka) {
        lblPoruka.setText(poruka);
        lblPoruka.setForeground(Color.red);
        btnpokusaj1.setEnabled(false);
        btnPokusaj2.setEnabled(false);
        btnpokusaj3.setEnabled(false);
        btnpokusaj4.setEnabled(false);

    }
}
